# apt_troubleshoot.yml
- name: Troubleshoot apt lock issues
  hosts: all
  become: yes
  tasks:
    # Check for any processes using the apt lock
    - name: Find any processes holding the apt lock
      shell: "lsof /var/lib/apt/lists/lock || true"
      register: lock_process_check
      changed_when: false

    - name: Display any processes holding the apt lock
      debug:
        var: lock_process_check.stdout_lines

    # Kill any processes holding the apt lock, if found
    - name: Kill processes holding the apt lock (if any)
      shell: "lsof -t /var/lib/apt/lists/lock | xargs -r kill -9"
      when: lock_process_check.stdout != ""

    # Use shell commands to remove lock files
    - name: Remove the apt lists lock file
      shell: "sudo rm -f /var/lib/apt/lists/lock"

    - name: Remove the apt archives lock file
      shell: "sudo rm -f /var/cache/apt/archives/lock"

    - name: Remove the dpkg lock file
      shell: "sudo rm -f /var/lib/dpkg/lock"

    # Reconfigure any dpkg packages if necessary, with explicit become
    - name: Reconfigure dpkg if it was interrupted
      command: dpkg --configure -a
      become: yes
      ignore_errors: yes
