# install_docker.yml
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    ### Pre-Task: Install Prerequisites Using Command Module
    - name: Install prerequisite packages for Docker (apt-transport-https, ca-certificates, curl, gnupg, lsb-release)
      command: >
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

    ### Add Docker’s Official GPG Key and Repository
    - name: Add Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Set up Docker repository
      command: echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    ### Update Package Index for Docker Installation
    - name: Update apt package index
      command: sudo apt-get update

    ### Install Docker Engine and Docker Compose Plugin
    - name: Install Docker Engine and Docker Compose
      command: sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

    ### Manage Docker as a Non-root User
    - name: Create Docker group if it does not exist
      group:
        name: docker
        state: present

    - name: Add the current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    ### Enable and Start Docker Service
    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    ### Verify Docker and Docker Compose Installation
    - name: Check Docker version
      command: docker --version
      register: docker_version

    - name: Display Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Check Docker Compose version
      command: docker compose version
      register: docker_compose_version

    - name: Display Docker Compose version
      debug:
        msg: "Docker Compose version: {{ docker_compose_version.stdout }}"
