# install_docker.yml
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    ### Step 1: Update and Install Required Packages
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    ### Step 2: Add Docker’s Official GPG Key and Repository
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Set up Docker repository
      apt_repository:
        repo: "deb [arch=arm64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    ### Step 3: Install Docker Engine and Docker Compose Plugin
    - name: Install Docker Engine and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    ### Step 4: Manage Docker as a Non-root User
    - name: Create Docker group if it does not exist
      group:
        name: docker
        state: present

    - name: Add the current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    ### Step 5: Enable and Start Docker
    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    ### Step 6: Verify Docker and Docker Compose Installation
    - name: Check Docker version
      command: docker --version
      register: docker_version

    - name: Display Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Check Docker Compose version
      command: docker compose version
      register: docker_compose_version

    - name: Display Docker Compose version
      debug:
        msg: "Docker Compose version: {{ docker_compose_version.stdout }}"
