- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    ### Pre-Task: Install Prerequisite Packages Using Command Module
    - name: Install prerequisite packages for Docker
      command: apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
      become: yes
      become_user: root

    ### Verify and Add Docker’s Official Repository
    - name: Verify Docker repository setup
      shell: echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
      become: yes
      become_user: root

    ### Update Package Index
    - name: Update apt package index
      command: apt-get update
      become: yes
      become_user: root

    ### Install Docker Packages
    - name: Install Docker Engine and Docker Compose
      command: apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      become: yes
      become_user: root
