# system_info.yml
- name: Gather system information
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display Hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Display IP Address
      debug:
        msg: "IP Address: {{ ansible_default_ipv4.address }}"

    - name: Display Operating System
      debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Display Uptime
      debug:
        msg: "Uptime: {{ (ansible_uptime_seconds | int // 3600) }} hours, {{ ((ansible_uptime_seconds | int % 3600) // 60) }} minutes, {{ (ansible_uptime_seconds | int % 60) }} seconds"

    - name: Display Total Memory
      debug:
        msg: "Total Memory: {{ ansible_memtotal_mb }} MB"

    - name: Display Available Memory
      debug:
        msg: "Available Memory: {{ ansible_memfree_mb }} MB"

    - name: Display Disk Usage
      debug:
        msg: "Root Partition Free Space: {{ ansible_mounts[0].size_available | int / 1024 / 1024 | round(2) }} MB out of {{ ansible_mounts[0].size_total | int / 1024 / 1024 | round(2) }} MB"
