# update_and_install.yml
- name: Update and install essential packages
  hosts: all
  tasks:
    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install essential packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - vim
